### ISSUE TITLE
Altering function body should invalidate the cache

### ISSUE THREAD

**Issue by joergen7** [joergen7/cre#4]

**Comment by jallmer** [comment]
Indeed, this was a bit problematic and I had to use cuneiform -c sometimes because of it.
Are you planning to only invalidate the cache for the deftask that was changed or for the complete workflow? I would prefer the former during development.

**Comment by joergen7** [comment]
Exactly. There is no reason to invalidate the cache if you didn't change anything. (If the data changes you have to use the -c option though.)
